/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package narutodatabase;

import java.awt.FlowLayout;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import java.sql.*;

/**
 *
 * @author USER
 */
public class DatabaseSummon extends javax.swing.JFrame {
    Cards c1;
    Statement stmt;
    ResultSet result;
    Connection con;
    
    
    /**
     * Creates new form DatabaseSummon
     */
    public DatabaseSummon() {
        try{   
    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/narutocards?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
        ,"root","voldemort");
    stmt=con.createStatement(); 
}catch(Exception e){ System.out.println(e);} 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\naruto cards\\EBRwhM4WwAAe0Xw.png")); // NOI18N
        getContentPane().add(jLabel1);

        jButton1.setText("Summon");
        jButton1.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    setLayout(new FlowLayout());
        //String s="C:\\Users\\USER\\Downloads\\SSGSSGogetaActiveSkill.wav";
        //String s="C:\\Users\\USER\\Downloads\\Final sounds NAruto\\Ikuyo min.wav";
        
        Cards sum=summon();
        String s=sum.getVoice();
        try {
            Ikuzo ik=new Ikuzo(s);
            ik.play();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(DatabaseSummon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DatabaseSummon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(DatabaseSummon.class.getName()).log(Level.SEVERE, null, ex);
        }
        //a.add(sum);
        System.out.print(sum.path);
        ImageIcon i=sum.getImg();
        setSize(getWidth(),i.getIconHeight());
        jLabel1.setIcon(i);
// TODO add your handling code here:
    }                                        
    public Cards summon() {        
        try {
            Random r;
            r = new Random();
            
            int x = r.nextInt(11);
            
            if(x==0)
                x=1;
            result=stmt.executeQuery("select * from narutocards.card where card_id="+x+";");
            result.next();
            String a=result.getString(2);
            String image="C:\\Users\\USER\\Downloads\\naruto cards\\"+result.getString(3);
            String c="C:\\Users\\USER\\Downloads\\Final sounds NAruto\\"+result.getString(5);
            ImageIcon b=new ImageIcon(image);
            c1=new Cards(a,b,c);
            
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseSummon.class.getName()).log(Level.SEVERE, null, ex);
        }
    return c1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseSummon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseSummon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseSummon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseSummon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseSummon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
